{{- if .Values.app.ingress.enabled -}}
{{- $chartlabels := include "generic-helm.labels" .}}
{{- $ingress := .Values.app.ingress }}
{{- range $ingress.objects }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-ingress
  labels:
    {{- $chartlabels  | nindent 4 }}
  annotations:
    {{- toYaml .annotations | trimSuffix "\n" | nindent 4 }}
spec:
  rules:
  {{- range .hosts}}
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          pathType: {{ .pathType | default "ImplementationSpecific" }}
          backend:
            service:
              name: {{ .backendsvc }}
              port:
                number: {{ .servicePort }}
    {{- end }}
  {{- end }}
  {{- end }}


