{{- $chartenvsecretname := include "chart.envsecretname" . }}
{{- if .Values.app.envSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $chartenvsecretname }}
  labels:
    {{- include "generic-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.app.envSecrets }}
  {{ $key }}: {{ $value | b64enc}}
  {{- end }}
{{- end }}