{{- if .Values.serviceAccount.created -}}
apiVersion: v1
kind: ServiceAccount
serviceAccountName: {{ include "generic-helm.serviceAccountName" . }}
metadata:
  name: {{ include "generic-helm.serviceAccountName" . }}
  labels:
    {{- include "generic-helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end -}}
